### PR TITLE
Support meson

### PR DESCRIPTION
**Pull request by afelinczak**
Hello,
I have added support for meson build system.
It works well, created ppa from it and retested autotools build after changes.
Tidy up debian folder as it wasn't possible to created Debian package on Ubuntu 20.04.

Looking forward for more contribution later (planning multi monitor support)

### CODE REVIEW

**Comment by zcot** [comment]
Great! That looks good @afelinczak!

I didn't see the additional build instructions added though. :zany_face: Did I miss those? :smiley: 

What is the commit about removing po files with non standard names?

**Comment by afelinczak** [comment]
Hey @zcot,
Thanks for your comment, I wasn't sure if you will be interested in migration to newer build system.
In my PR translations are renamed to match meson system defaults. I will try to review this again, maybe will be able to find way to keep old files names.
Will also add build instructions and look again on build params - currently in PR meson is producing binary for debugging.

Regards,
Arek

**Comment by zcot** [comment]
Hi Arek,

Did you review this PR at all?

If I use the sample instruction here: https://mesonbuild.com/Quick-guide.html#compiling-a-meson-project then the project does not work.

If I mangle it, then I can have some success, but there is no po files available.

**Comment by afelinczak** [comment]
That was long time ago.
It was built with sequence of commands:
meson build
cd build
ninja
sudo ninja install  

Problem is I never got translation working as po file names are not standard in Conky-manager. That is why in Pr they are renamed.

**Comment by afelinczak** [comment]
Btw, binary builds in my ppa are built using this branch. I was migrating clipit to meson as well, but recently it was found that some translations were missing from meson builds (some strings was translated while others not).
We rollback clipit builds to autotools because of this recently.

**Comment by zcot** [comment]
Ok, good. We do this.

Thank you! :+1:

**Pull request merged**
